# Generated by Django 4.2.1 on 2023-05-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
